---
project_name: wally

release:
  github:
    owner: quickstar
    name: wally

checksum: {}

builds:
  - binary: wally
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    main: ./main.go

archives:
  - id: binary
    format: binary
  - id: default
    format: tar.gz
