---
project_name: wally

release:
  github:
    owner: quickstar
    name: wally

builds:
  - binary: wally
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    main: ./main.go

archives:
  - format: tar.gz
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
brews:
  - name: wally
    tap:
      owner: quickstar
      name: homebrew-tap
    description: "Fetch the wallpaper from Bing, Reddit, Unsplash ..."
